### ISSUE TITLE
spring-cloud-etcd-config

### ISSUE THREAD

**Issue by lburgazzoli** [spring-cloud-incubator/spring-cloud-etcd#1]
I've recently started working to spring-cloud-etcd-* then I've discovered this incubator project. 

My code is hosted on my profile https://github.com/lburgazzoli/lb-spring and I did some changes to make it similar to this project as I'd more than happy to contribute the spring-cloud-etcd-config implementation if you like it, let me know if you want me to send a PR

**Comment by spencergibb** [comment]
Pull requests are welcome!

**Comment by lburgazzoli** [comment]
Firs PR done: https://github.com/spring-cloud-incubator/spring-cloud-etcd/pull/2

**Comment by spencergibb** [comment]
fixed via 05cfc99504e28f655d24bb3f3abf59249c3da7f1
