### ISSUE TITLE
Feign Etcd client implementation

### ISSUE THREAD

**Issue by lburgazzoli** [spring-cloud-incubator/spring-cloud-etcd#15]
As today spring-cloud-etcd uses etcd4j (project to which I've contribute a few things) as Etcd client but as Netflix's Feign is already a dependency I was wondering if it would make sense to implement a custom Etcd client to:
- reduce dependencies and base the implementation on common SpringCloudOSS technologies 
- tailoring the client to the needs of spring-cloud-etcd (i.e. support for Etcd healt indicator)

Writing an Etcd client with Netflix's Feign is very easy.

**Comment by spencergibb** [comment]
In spring-cloud-consul I [specifically removed](https://github.com/spring-cloud/spring-cloud-consul/commit/57ded28fe564cf911d8e9164c3bd41872f17bba8) a feign consul client. I'm not keen on maintaining clients to all these different services.

**Comment by lburgazzoli** [comment]
Ah ok, so it make sense to stick with ecd4j
