### ISSUE TITLE
Support for runtime changes of @ConfigurationProperties and @RefreshScope via Etcd

### ISSUE THREAD

**Issue by makobernal** [spring-cloud-incubator/spring-cloud-etcd#23]
Properties and beans annotated with @ConfigurationProperties and @RefreshScope can be re-bound at runtime when receiving a EnvironmentChangedEvent.

spring-cloud-etcd could implement something similar by this by listening to changes done to configuration values on Etcd (request to etcd for values with wait, perhaps?)

Are there any plans on implementing this pattern?

**Comment by spencergibb** [comment]
Yes, that would be a good addition. Pull Requests welcome.
