### ISSUE TITLE
spring cloud etcd not update?

### ISSUE THREAD

**Issue by dragontree101** [spring-cloud-incubator/spring-cloud-etcd#26]
spring cloud etcd not update?
 i found spring cloud consul and spring cloud zookeeper always update，but spring cloud etcd have not update serval month， i want to use etcd to do service discovery, could i use spring-cloud-etcd this project? thanks

**Comment by marcingrzejszczak** [comment]
This project is in the incubating phase so it's definitely not production ready. There is not even a milestone released. You can use only snapshots.
