### ISSUE TITLE
Support spring-cloud-config style hierarchy for spring-cloud-etcd-config

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud-incubator/spring-cloud-etcd#3]
Spring cloud config finds config files with the following precedence:

* `<appname>-<profilename>.{yml,properties}`
* `<appname>.{yml,properties}`
* `application-<profilename>.{yml,properties}`
* `application.{yml,properties}`

[Spring Cloud Consul](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-config/src/main/java/org/springframework/cloud/consul/config/ConsulPropertySourceLocator.java#L54-L72) approximates this using a different directory for each, ie:

* `/config/<appname>,<profilename>/`
* `/config/<appname>/`
* `/config/application,<profilename>/`
* `/config/application/`

It adds a `PropertySource` for each in the correct order.

**Comment by spencergibb** [comment]
@lburgazzoli fyi

**Comment by lburgazzoli** [comment]
It should already do something similar or at least it was my intention to do so but I will have a look

**Comment by lburgazzoli** [comment]
At the moment, for an application named testEtcdApp with test1 and test2 as active profiles, it creates the PropertySource in the following order:

* config/testEtcdApp-test2
* config/testEtcdApp-test1
* config/testEtcdApp
* config/application-test2
* config/application-test1
* config/application

**Comment by spencergibb** [comment]
Yeah, looks like it.  I missed it when I reviewed it.

**Comment by spencergibb** [comment]
Closed via 05cfc99504e28f655d24bb3f3abf59249c3da7f1
