### ISSUE TITLE
I want to use etcd as the backend for config server.

### ISSUE THREAD

**Issue by regardfs** [spring-cloud-incubator/spring-cloud-etcd#45]
Hi, all:
I want to use etcd as the backend for config server. Does this spring-cloud-etcd support this function?

**Comment by spencergibb** [comment]
No, and a request like this would go in spring-cloud-config.

**Comment by regardfs** [comment]
@spencergibb I do it by myself, but according to confidentiality agreement I could not push it to  github , may i show u in other way? by email?

**Comment by spencergibb** [comment]
If you can't provide it via a pull request and sign the contributor agreement, we're unable to accept the contribution.
